### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by Madis0** [ye-yu/fabric-dynamic-lights#1]
The readme says the following:

> By default, the mod will only render the nearest 4 entities that are eligible for dynamic lights, which is the lowest setting for this mod.

> The default setting for light radius is level 3, which is the medium level. Increase this to get a brighter dynamic light, and reduce this to get a faster performance.

yet the mod's `dynamic-lights` folder is empty, so it is unclear how to configure those two values.

It also says 

> In your game directory, find the directory config and create a directory named dynamic-lights. In here, drop all your configuration files, and the mod will iterate over each file to apply your new configuration.

but not what the configs should be named.

Tested this with the version 1.0.0 from PMC for that matter.

**Comment by Madis0** [comment]
Ah, I figured it out:

> If you are interested to increase the settings, head to the video settings of your option screen.

**Comment by ye-yu** [comment]
thanks for the review, 

>By default, the mod will only render the nearest 4 entities that are eligible for dynamic lights, which is the lowest setting for this mod. The default setting for light radius is level 3, which is the medium level. Increase this to get a brighter dynamic light, and reduce this to get a faster performance.

This one, you can head into the video settings of minecraft:

![image](https://user-images.githubusercontent.com/30603031/166101330-c2ca37b9-febb-4b0c-9caf-12a245a3ab66.png)

And scroll down to see the dynamic options

---

>In your game directory, find the directory config and create a directory named dynamic-lights. In here, drop all your configuration files, and the mod will iterate over each file to apply your new configuration.

Ah sorry for this one I have not fully tested it yet, but the source code where the mod is reading the config files is here: https://github.com/ye-yu/fabric-dynamic-lights/blob/82595ed0f016a364bbe7b4e17f33d9b56d32e732/src/main/java/yeyu/dynamiclights/client/DynamicLightsConfig.java#L120

If you are using multimc, at the right sidebar, you can click on `Edit Instance` > `Open .minecraft` and then you will be able to see the directory named `config`. Go inside and you should be able to see another directory called `dynamic-lights`. If you dont see any of these directories, try running minecraft first and then exit and repeat again. The file name can be anything, but for you can try using `*.yaml` for readability. File content format must follow accordingly
