### ISSUE TITLE
Options are stored in the wrong location

### ISSUE THREAD

**Issue by Madis0** [ye-yu/fabric-dynamic-lights#2]
The options are stored in `.minecraft\dynamiclights-options.txt` while they should be in `.minecraft\config\dynamic-lights\options.yaml`.

**Comment by Madis0** [comment]
Why not?

**Comment by ye-yu** [comment]
in my understanding, `dynamic-lights/*.yaml` should contain user-defined dynamic light configurations (currently experimental). plus, the options location is following minecraft's default options file as well `.minecraft/options.txt`.

**Comment by Madis0** [comment]
If you want to separate user configs and main config, that's fine. But the main config should still be in the `config` folder, that is the standard practice for mods for a long time. Only the Minecraft's own config should be in `.minecraft` root folder.

So what about `.minecraft\config\dynamic-lights-options.yaml` and `.minecraft\config\dynamic-lights\`?

**Comment by ye-yu** [comment]
alright will do

**Comment by ye-yu** [comment]
fixed in edef0cef4f4a9abc2925e43ed28f93544108b1fd
