### ISSUE TITLE
Custom configs don't seem to work

### ISSUE THREAD

**Issue by Madis0** [ye-yu/fabric-dynamic-lights#5]
**Edit: as I suspected, they actually do work, it's just a mistake in the readme. See #7**

---
Fabric Dynamic Lights 1.0.0, compiled from source (as of [168f090](https://github.com/ye-yu/fabric-dynamic-lights/commit/168f090d947ded922ed366a944d93a407b0dcd00))
`.minecraft\config\dynamic-lights\stick.yaml`
```
# a compulsory field
type: item

# minecraft id for the item
id: minecraft:stick

# light emitted based on a static value
# if left empty, the default value
# is 0
light source offset: 10
```
`.minecraft\config\dynamic-lights\pig.yaml`
```
# a compulsory field
type: entity

# minecraft id for the entity
id: minecraft:pig

# light emitted will be based on
# held items, has a stronger precedence
# over the next field.
# if left empty, the default value
# is false
light strength by item: false

# light emitted based on a static value
# if left empty, the default value
# is 0
light source offset: 10
```
![2022-04-30_14 31 57](https://user-images.githubusercontent.com/8611110/166103761-9b2712fc-30cd-4cd3-8fd6-b216b63c79f8.png)

**Comment by ye-yu** [comment]
fixed in https://github.com/ye-yu/fabric-dynamic-lights/tree/feat/1.0.3+1.18.2, forgot which commit, it works now, sample that is working

```yml
type: entity
id: minecraft:spider
default light level: 8
```
