### ISSUE TITLE
Dynamic Lights Performance setting doesn't save

### ISSUE THREAD

**Issue by Madis0** [ye-yu/fabric-dynamic-lights#6]
Fabric Dynamic Lights 1.0.0, compiled from source (as of [168f090](https://github.com/ye-yu/fabric-dynamic-lights/commit/168f090d947ded922ed366a944d93a407b0dcd00))

1. Run Minecraft with the mod
2. Open Video settings, set "DL. Performance" to some other value
3. Close the game, notice that it is changed in the config file
4. Launch the game again, check Video settings
5. The setting says "DL. Performance: EASE" again

**Comment by ye-yu** [comment]
Fixed in 44393ab84f40233a946ce96778c0a84d69f8e142
