### ISSUE TITLE
Dynamic Light Level option should use numbers

### ISSUE THREAD

**Issue by Madis0** [ye-yu/fabric-dynamic-lights#8]
Vanilla uses numbers for the light level, [even for the new creative-only block](https://minecraft.fandom.com/wiki/Light_Block), so this mod should do the same for the "Dyn. Light Level" option.

Edit: looking at the code, it doesn't seem to behave quite like vanilla. I'm not sure how exactly it works but I think mimicing vanilla would make it more understandable.

```
    OFF(10, 0f),
    MINIMAL(6, .8f),
    HEAVY(12, 0.8f),
    POWERFUL(18, 1f);
 ```

**Comment by ye-yu** [comment]
will refactor code namings and UI on a different milestone. what i have in mind at the moment is that Dyn. Light Level should be renamed to Dyn. Light Spreadness

but i also have plans to reduce game options to simplify the settings. after all, the mod is just a mini dynamic lights, so i'd figure game options should be as mini as possible too
