### ISSUE TITLE
Stutter while a torch is in hand

### ISSUE THREAD

**Issue by Uranite** [ye-yu/fabric-dynamic-lights#9]
![2022-05-01_22 27 14](https://user-images.githubusercontent.com/62639703/166152905-5d368422-c2cb-4830-ad72-c07134a8cc55.png)
I'm having a pretty bad stutter
However there is no stutter at all when the torch is placed
![2022-05-01_22 33 45](https://user-images.githubusercontent.com/62639703/166153162-cc6a1bdb-d59c-4be8-87f8-8e5711b2c5fa.png)

**Comment by ye-yu** [comment]
Thanks for the feedback! I have been experimenting a lot of stuffs, but I agree a lot of stuffs can be worse than the existing dynamic light mods.

I have just released a build update v1.0.2, can you try rerun this again and see if it performs better than before?  Here is the settings that I felt was the best for me:

Dyn. Light Level: HEAVY
Dyn. Light Entities: 3
DL. Performance: SMOOTH
DL. Precision: MINIMAL

mod link: https://modrinth.com/mod/mdl/version/1.0.2

**Comment by ye-yu** [comment]
oh this is using sodium, can you add experiment with these settings too?

- Chunk threads
- smooth lightings -> minimum

see if it reduces the stutterings too, thanks!

**Comment by Uranite** [comment]
It's better, but I think DL. Performance should be on EASE or FASTER (I lean more toward faster), since having it on smooth make things feel stuttery and it gives you bad frame time
All tested with fabulously optimized modpack and starlight (I tried testing without starlight but since without it, it causes a really bad stutter so I didn't bother, but you could try with phosphor and see if it gives better frame time, but that's very unlikely)
And it seems having sodium makes the stutter worse?
Here is DL. Performance Smooth without sodium 
![No Sodium](https://user-images.githubusercontent.com/62639703/167169877-c92e4c39-4a1e-4651-93f5-794a35d81de4.png)

Here is the same settings but with sodium
![Always Defer Off Chunk Thread Default](https://user-images.githubusercontent.com/62639703/167169704-59b5d3e1-fdfd-49ee-8165-1cffdef00cb4.png)

But luckily the stutter can be reduced a little by giving it more chunk threads, but its too small of an improvement. And using more chunk threads may negatively impact frame times
![Chunk Update Threads 4](https://user-images.githubusercontent.com/62639703/167170284-c29c4bb4-171b-42f4-a0e7-546f33074af2.png)

Here is Always Defer Chunk Updates On, certainly does make the stutter better, could cause [issue](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/287), but definitely turn it on and if it doesn't cause any issue for you, then leave it on
![Chunk Thread Default Always Defer Chunk Updates on](https://user-images.githubusercontent.com/62639703/167172354-1eff2301-f32d-4d33-a0e4-be383bdb86cf.png)

And I tried Smooth Lightning to minimum on both with and without sodium, and I didn't notice any difference (And it seems the sodium equivalent of minimum is off(?), since I changed smooth lighting to minimum without sodium and when I re enabled sodium it is off)

And it seems that Glow Lichen causes bad frame time for some reason, unlike placed torch 
![2022-05-06_23 26 41](https://user-images.githubusercontent.com/62639703/167173749-5bd53eaa-f283-4a9b-b428-a1e254affe53.png)

You could leave DL. Performance at SMOOTH but you need to enable Always Defer Chunk Updates to have a pleasant experience

**Comment by ye-yu** [comment]
Thanks a lot for the detailed analysis! This will be helpful later for my mod compatibility testing in the future. For now, I will close this issue as resolved (using latest build or using Sodium with defer chunk updates "on")
